# -------------------------------------------------------- service
server:
  port: 8083
spring:
  application:
    name: service-1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test01
    username: root
    password: 123456
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test01
      username: root
      password: 123456

# -------------------------------------------------------- log
logging:
  #  指明 log4j2.yml 的位置
  config: classpath:log4j2.yml
  level:
    root: info
    org.springframework.boot.autoconfigure: info

# -------------------------------------------------------- Knife4j
knife4j:
  production: false
  # 开启增强配置
  enable: true
  setting:
    enable-group: true
  # 设置用户名和密码
  basic:
    enable: true
    username: admin
    password: 123456

# -------------------------------------------------------- swagger
springdoc:
  api-docs:
    #  是否启用 Swagger UI
    enabled: true
    # OpenAPI 规范文档路径，默认为 /v3/api-docs
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    # Swagger UI 页面访问路径，默认为 /swagger-ui.html
    path: /swagger-ui.html

# -------------------------------------------------------- mysql


# --------------------------------------------------------

